module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/IS276Wg9zcuCnJRiMDI64g',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/xney4v.jpg',
    NEWSLETTER_JID: '120363425061263455@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗝𝗔𝗠𝗔𝗟𝗜 𝗠𝗗',
    OWNER_NAME: '𝗝𝗔𝗠𝗔𝗟𝗜 𝗧𝗘𝗖𝗛',
    OWNER_NUMBER: '255784062158',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝗝𝗔𝗠𝗔𝗟𝗜 𝗧𝗘𝗖𝗛',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC7AgJK5cD71vGIpO3h',
};
